"""Remove driver and available_seats columns

Revision ID: 260f51b4003d
Revises: 6fb0f5b3ea17
Create Date: 2025-05-30 13:55:52.407856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260f51b4003d'
down_revision = '6fb0f5b3ea17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.alter_column('contact_birthdate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.drop_column('available_seats')
        batch_op.drop_column('is_driver')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_driver', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('available_seats', sa.INTEGER(), nullable=True))
        batch_op.alter_column('contact_birthdate',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
